### ISSUE TITLE
Make use of subject and session input text fields instead of dropdown lists. 

### ISSUE THREAD

**Issue by rutgervandeelen** [Donders-Institute/data-streamer#24]
In the `streamer-ui`, make use of subject and session input text fields instead of dropdown lists. 

Note: the cascading selection fields should be same as in the calendar booking form:
`[Project, Subject, Session, Modality]`

**Comment by rutgervandeelen** [comment]
See commit ca5bb88ada3ccd38662847bf3a551f60328cd0e3. Now we expect 1- or 2-digit number for subject and session label.

**Comment by robertoostenveld** [comment]
Let me also ping @marcelzwiers on this. 

It should be possible to specify both subject and session manually using the form [a-zA-Z0-9]*, i.e. repeats of characters and/or digits. Right now this is already used for session (which is usually mri01 or meg01). For subjects it is needed so that project specific identifiers can be used, e.g. such as those used in POM.

**Comment by rutgervandeelen** [comment]
For your information: 
I currently use `/project/{projectnumber}/raw/sub-{subjectlabel}/ses-{datatype}{sessionlabel}` as the project storage destination path. Currently `{subjectlabel}` and `{sessionlabel}` have the form `^[0-9]{1,2}$`.

**Comment by robertoostenveld** [comment]
Then that needs to be fixed: 
1) datatype should not be part of the sessionlabel, the user has to specify himself that the data is recorded in the mri01 session (e.g. for presentation files), or in a separate behavioural session (which the user might want to represent as beh01). 
2) subjectlabel  and sessionlabel don't have to be numeric (that restriction applies to the calendar, but should not apply to the labstreamer) 

Within one session (e.g. a person coming to the mri lab, hence the sessionlabel mri01), multiple types of data can be recorded. On the target disk location those should be merged, for example as

```
root/sub-POM1783/ses-mri-01/01_localizer/
root/sub-POM1783/ses-mri-01/02_AAHead_Scout_32ch-head-coil/
root/sub-POM1783/ses-mri-01/...
root/sub-POM1783/ses-mri-01/06_t2_haste_sag_p2/
root/sub-POM1783/ses-mri-01/07_cmrr_RS_mbep2d_bold|_2.2x2.2_TR860/
root/sub-POM1783/ses-mri-01/08_diffusion_b1000_68dirs_1.8_slab/
root/sub-POM1783/ses-mri-01/09_t2_swi3d_tra_p2_0.7x0.7x0.7_TE20/
root/sub-POM1783/ses-mri-01/...
root/sub-POM1783/ses-mri-01/13_AAHead_Scout_32ch-head-coil/
root/sub-POM1783/ses-mri-01/...
root/sub-POM1783/ses-mri-01/17_tfl_mp2rage/
root/sub-POM1783/ses-mri-01/...
root/sub-POM1783/ses-mri-01/22_thal_svs_edit_859D-1.8x2.4x1.8_128av/
root/sub-POM1783/ses-mri-01/23_mot_svs_edit_859D-1.8x2.4x1.8_96av/
root/sub-POM1783/ses-mri-01/eeg/
root/sub-POM1783/ses-mri-01/beh/
root/sub-POM1783/ses-mri-01/emg/
root/sub-POM1783/ses-mri-01/eyetracking/
root/sub-POM1783/ses-mri-01/video/
```

The first part (starting with the scan number from 00 to 23) are the different MRI data types that are recorded and streamed automatically. The BIDScoiner will map them (later) to more meaningful datatypes, such as `anat`, `func`, `dwi` or `fieldmap`. 

The latter ones (`eeg`, `beh`, `eyetracking`, etc) are already recognizable, since added by the researcher in the labstreamer webinterface. 

So the user of the webinterface specifies
- project from list
- subject=xxx as [a-zA-Z0-9]*
- session=yyy as [a-zA-Z0-9]*
- datatype=zzz from list, optionally other as [a-z]*
and the datafiles go to project/sub-xxx/ses-yyy/zzz/...

**Comment by robertoostenveld** [comment]
Please read https://bids-specification.readthedocs.io/en/stable/02-common-principles.html and let me know if anything is unclear.

**Comment by robertoostenveld** [comment]
Oh, and note that for DCCN raw data, we organize it in a _BIDS-like_ structure, not in a **proper** BIDS-structure (that only comes after bidscoiner or [data2bids](http://www.fieldtriptoolbox.org/reference/data2bids/)) . That is why the dataypes in the directory names deviate in some places, and why we don't impose file format restrictions. But the directory structure is largely similar to BIDS.

**Comment by marcelzwiers** [comment]
I think this is a good proposal, and allows for a simple extension into the
current data flow (e.g. for simultaneous data-type recordings, as well as
for free-format data types into ses-[free-format] session types.

Op di 27 aug. 2019 om 17:50 schreef Robert Oostenveld <
notifications@github.com>:

**Comment by marcelzwiers** [comment]
I can't remember how I constructed the regexp anymore (:-p), and I think
the replace command is redundant, but this is what I use to clean-up
user-entered strings that have to be used as bids values:

def cleanup_value(label):
    """
    Converts a given label to a cleaned-up label that can be used as a BIDS
label. Remove leading and trailing spaces;
    convert other spaces, special BIDS characters and anything that is not
an alphanumeric to a ''. This will for
    example map "Joe's reward_task" to "Joesrewardtask"

    :param label:   The given label that potentially contains undesired
characters
    :return:        The cleaned-up / BIDS-valid label
    """

    if label is None:
        return label

    special_characters = (' ', '_', '-','.')

    for special in special_characters:
        label = str(label).strip().replace(special, '')

    return re.sub(r'(?u)[^-\w.]', '', label)

Op di 27 aug. 2019 om 15:43 schreef Robert Oostenveld <
notifications@github.com>:

**Comment by rutgervandeelen** [comment]
@robertoostenveld and @marcelzwiers Thank you for the clarification. 

I have some questions concerning the `xxx`, `yyy` and `zzz` strings:

1. Do I understand correctly that for the example `root/sub-POM1783/ses-mri-01/22_thal_svs_edit_859D-1.8x2.4x1.8_128av/` gives `xxx =POM1783` , `yyy = mri-01` and `zzz = 22_thal_svs_edit_859D-1.8x2.4x1.8_128av`?

2. Using regex `[a-zA-Z0-9]*` allows `yyy = mri01` but not `yyy = mri-01`. Should we make it  `[a-zA-Z0-9\-]*` instead to include dashes (i.e. `-`)?

3. In this example, `zzz` is not of the form  `[a-z]*`?

4. Using regex `[a-zA-Z0-9]*` and `[a-z]*` implies empty strings are also allowed. Should we use `[a-zA-Z0-9]+` and `[a-z]+` instead (i.e. one or more characters instead of zero or more characters)?  If not, how to deal with the empty strings (i.e. in the target destination path)?

5. Perhaps we should not use a `cleanup_value` kind of function in the data streamer UI like Marcel suggests? As Robert mentions this should be dealt with the conversion using `data2bids` or `bidscoiner` at a later stage?

**Comment by robertoostenveld** [comment]
1) yes, except that the dash in `mri-01` is a typo that I made in a previous comment. The session should be `mri01`. 
2) no, dashes are not allowed. There are used to separate the key from the value in the key-value list in the filename. E.g. `key1-value1_key2-value2`. Underscores separate the key-value pairs from each other.
3) I am no regexp expert, please ask again if this pertains to functional design or implementation choices.
4) empty strings are not allowed. The implementation does not have to use regular expressions either, just validate that the input is a non-empty series of characters and digits.
5) ?? I guess this is a question for @marcelzwiers

**Comment by rutgervandeelen** [comment]
See `https://streamer-acc.dccn.nl` for demo.

Concerning the 1 to 5 above:
* The subject and session label are now free text input fields. The regex validation is `[a-zA-Z0-9]+` (not empty, one or more characters, no special characters)
* The data type other is a free text input field. The regex valdiation is `[a-z]+` (not empty, one or more lowercase characters, no numbers, no special characters)
* No cleanup function is used on the input fields

I am closing this issue now.
