### ISSUE TITLE
Display all destination folders in the Research Data Uploader UI

### ISSUE THREAD

**Issue by marcelzwiers** [Donders-Institute/data-streamer#242]
Currently, when a user wants to upload data using the Research Data Uploader, the UI suggests that the data is always only uploaded to the project folder on central storage. In reality, however, a big asset of the uploader is that it can also upload the data to the Donders repository. It would be good if this is reflected in the UI (e.g. as shown in the mock-up below), so the researcher can become more aware of the location where the data is copied to.

![image](https://user-images.githubusercontent.com/15156015/150106860-58adb74d-c1f2-43d8-912c-d6071ad11a6a.png)

**Comment by hurngchunlee** [comment]
@marcelzwiers I have implemented it.  Before I update the production, could you please check the acceptance to see if you have further comment?  The acceptance is https://streamer-acc.dccn.nl/

The DR path represents the WebDAV namespace, given that the majority of users can recognize in their WebDAV clients.

The collection namespace linked to the project is resolved on-demand (via the API route of "streamer --> stager --> DR") so it will take sometime to get it. If the project doesn't have its DAC (or it fails to resolve it due to, e.g. timeout), a message `no available destination in the Donders Repository` is shown.

**Comment by marcelzwiers** [comment]
Looks great and I think it is very useful. One more (hopefully minor) suggestion for improvement is that perhaps you can show the project title after a project number is selected. That would make it easier for users to select the right project (especially if you have many projects)

**Comment by hurngchunlee** [comment]
@marcelzwiers I tried ... but given the code spaghetti done by Rutger, it will take some time to refactor all his code to display the project title.  If it is not very important, I suggest to deploy it to the production as it is now, and follow it up in a separate issue.  What do you think?

**Comment by marcelzwiers** [comment]
Yes, that's fine with me.
