### ISSUE TITLE
Create catchall project and DAC for all lab data streamed from the UI

### ISSUE THREAD

**Issue by rutgervandeelen** [Donders-Institute/data-streamer#26]
Implement catchall for all lab data streamed

**Comment by hurngchunlee** [comment]
I have created a project in the project database, using the financial code `3055000` which refers to __General Lab Facility__.  The resulting project number is `3055000.01`.

The DAC is also created accordingly in the Donders Repository: https://data.donders.ru.nl/collections/di/dccn/DAC_3055000.01_467

@rutgervandeelen could you login to the Donders Repository once so that I can add you to the collection?

**Comment by rutgervandeelen** [comment]
@hurngchunlee I have just logged in to the Donders Repository.

**Comment by hurngchunlee** [comment]
Both DAC collection and project storage for 3055000.01 are created successfully.  Closing the issue.
